#!/usr/bin/env python3
# R220/R221 eraser map data (FINAL v6.1) - auto-serialized.
# v6 (R221): the no-op entry ('if i know'->'if i know') removed; the
#   already-clean guard added to every consumer (census/apply/rewrite).
# v6.1 (R221, the over-reach audit): FOUR LEGIT-WORD KEYS REMOVED after the
#   history-census eyeball pass proved they corrupt non-owner text:
#     differ->different (corrupted 42 agent-prose lines: 'headers differ per
#       convention' -> 'different per convention' etc.; ALL 42 reverted; the
#       owner context is covered by the anchored phrase 'are named differ')
#     dont->don't (corrupted 16 UI-copy quotes 'Dont be a flake' + the
#       analysis lines; ALL reverted; the owner contexts are covered by nine
#       anchored phrases below)
#     strat->start (the guitar 'American Standard Strat' in mock listings;
#       zero owner contexts)
#     githooks->git hooks (the git-scm.com/docs/githooks URL in
#       setup-git-hooks.sh; zero owner contexts)
#   The R220 claim 'no legit-word keys' was falsified by these four; the
#   v6.1 rule is enforced: every word key must be a NON-word (no legitimate
#   English/domain usage anywhere in the repo's evidence).

WORD_MAP = {'aaliys': 'analysis',
 'aand': 'and',
 'abd': 'and',
 'abpove': 'above',
 'accep': 'accept',
 'accese': 'access',
 'accesibitly': 'accessibility',
 'accest': 'accept',
 'accet': 'accept',
 'accomodate': 'accommodate',
 'accout': 'account',
 'accoutn': 'account',
 'accpet': 'accept',
 'accurlty': 'accurate',
 'accwpt': 'accept',
 'acecpt': 'accept',
 'acestic': 'aesthetic',
 'acheive': 'achieve',
 'achiv': 'achieve',
 'acitve': 'active',
 'acknowlege': 'acknowledge',
 'acorss': 'across',
 'acount': 'account',
 'acrodss': 'across',
 'actualy': 'actually',
 'acualrt': 'actual',
 'addrdres': 'address',
 'addrese': 'address',
 'adn': 'and',
 'adresse': 'address',
 'aefer': 'after',
 'aeshtetic': 'aesthetic',
 'afeer': 'after',
 'afer': 'after',
 'afeter': 'after',
 'afetr': 'after',
 'aget': 'agent',
 'agetn': 'agent',
 'agiang': 'again',
 'aginst': 'against',
 'agisnt': 'against',
 'agn': 'again',
 'agna': 'again',
 'agnet': 'agent',
 'agpond': 'upon',
 'agressive': 'aggressive',
 'ahd': 'and',
 'ahinve': 'achieve',
 'ahve': 'have',
 'aignet': 'agent',
 'aisl': 'also',
 'aking': 'asking',
 'aksed': 'asked',
 'aksin': 'asking',
 'alll': 'all',
 'allready': 'already',
 'allso': 'also',
 'alot': 'a lot',
 'alowasy': 'always',
 'alreaduy': 'already',
 'alreayd': 'already',
 'alswasy': 'always',
 'alternitive': 'alternative',
 'alwasy': 'always',
 'alwo': 'allow',
 'alwoas': 'always',
 'amek': 'make',
 'anailys': 'analysis',
 'analiy': 'analysis',
 'analiys': 'analysis',
 'analiyys': 'analysis',
 'analsiys': 'analysis',
 'analsyis': 'analysis',
 'analtiys': 'analysis',
 'analtyis': 'analysis',
 'analyis': 'analysis',
 'analyize': 'analyze',
 'analyosi': 'analysis',
 'analys': 'analysis',
 'analzye': 'analyze',
 'analzys': 'analyze',
 'anaoyrher': 'another',
 'anayls': 'analysis',
 'anaylsis': 'analysis',
 'anaylze': 'analyze',
 'anayze': 'analyze',
 'ancarlilty': 'ancillary',
 'andothenr': 'another',
 'andother': 'another',
 'aniy': 'analysis',
 'anlaliy': 'analyze',
 'anltiys': 'analysis',
 'anlyi': 'analysis',
 'anlyis': 'analysis',
 'anlyz': 'analyze',
 'anlzye': 'analyze',
 'anot': 'not',
 'anotehr': 'another',
 'ansl': 'and',
 'anslits': 'analysis',
 'antlyos': 'analysis',
 'anual': 'annual',
 'anylis': 'analysis',
 'anyls': 'analyze',
 'anyoher': 'another',
 'anyting': 'anything',
 'aovid': 'avoid',
 'apge': 'page',
 'aply': 'apply',
 'apond': 'upon',
 'apoun': 'upon',
 'apove': 'approve',
 'apoved': 'approved',
 'apper': 'appear',
 'appl': 'apply',
 'applyed': 'applied',
 'apporch': 'approach',
 'apporve': 'approve',
 'appove': 'approve',
 'approch': 'approach',
 'aprove': 'approve',
 'aprpoval': 'approval',
 'aredeploy': 'redeploy',
 'arelady': 'already',
 'arguement': 'argument',
 'arhived': 'archived',
 'ases': 'assess',
 'asess': 'assess',
 'asl': 'also',
 'aslo': 'also',
 'asme': 'same',
 'aso': 'also',
 'assesss': 'assess',
 'assses': 'assess',
 'assuem': 'assume',
 'asteic': 'aesthetic',
 'asume': 'assume',
 'aswell': 'as well',
 'atbases': 'databases',
 'atention': 'attention',
 'athiest': 'atheist',
 'attept': 'attempt',
 'atuaometed': 'automated',
 'auitdd': 'audited',
 'auits': 'audits',
 'aurts': 'audits',
 'autmatilcy': 'automatically',
 'autoamkte': 'automated',
 'autoamte': 'automate',
 'autoamted': 'automated',
 'autoamtily': 'automatically',
 'autoamtion': 'automation',
 'autoamuilty': 'automatically',
 'automatily': 'automatically',
 'auttlyily': 'automatically',
 'availabe': 'available',
 'availble': 'available',
 'aviod': 'avoid',
 'baed': 'based',
 'basicly': 'basically',
 'beacuse': 'because',
 'beca': 'because',
 'becasue': 'because',
 'beciase': 'because',
 'becuase': 'because',
 'befeor': 'before',
 'befoer': 'before',
 'befor': 'before',
 'befroe': 'before',
 'begining': 'beginning',
 'behavoir': 'behavior',
 'behined': 'behind',
 'beofre': 'before',
 'beuse': 'because',
 'bfore': 'before',
 'bheivoer': 'behavior',
 'blaocking': 'blocking',
 'ble': 'able',
 'blokck': 'block',
 'blth': 'both',
 'bnew': 'new',
 'borard': 'board',
 'brainstrom': 'brainstorm',
 'breka': 'breakdown',
 'broswer': 'browser',
 'bsed': 'based',
 'btton': 'button',
 'buiding': 'building',
 'buidl': 'build',
 'buld': 'build',
 'buton': 'button',
 'buuild': 'build',
 'bypaas': 'bypass',
 'cahgnes': 'changes',
 'calender': 'calendar',
 'calssic': 'classic',
 'cant': "can't",
 'catagory': 'category',
 'ceratin': 'certain',
 'certin': 'certain',
 'chek': 'check',
 'chekc': 'check',
 'chines': 'chinese',
 'chinse': 'chinese',
 'chinsese': 'chinese',
 'chinsnese': 'chinese',
 'choosedocs': 'choose',
 'citieng': 'citing',
 'cladue': 'claude',
 'clcik': 'click',
 'clearlty': 'clearly',
 'clik': 'click',
 'clodudflare': 'cloudflare',
 'cloudfalre': 'cloudflare',
 'cna': 'can',
 'cnat': "can't",
 'coamltion': 'completion',
 'coamper': 'compare',
 'cofusing': 'focusing',
 'collaegue': 'colleague',
 'collegue': 'colleague',
 'comapelt': 'complete',
 'comaper': 'compare',
 'comapre': 'compare',
 'comaprisson': 'comparison',
 'comeplt': 'complete',
 'comeplted': 'completed',
 'commbine': 'combine',
 'comming': 'coming',
 'commited': 'committed',
 'commplent': 'complement',
 'commplety': 'completely',
 'compair': 'compare',
 'compleatly': 'completely',
 'complet': 'complete',
 'concientious': 'conscientious',
 'conenct': 'connect',
 'confrim': 'confirm',
 'confrm': 'confirm',
 'connsied': 'considered',
 'conrol': 'control',
 'consistant': 'consistent',
 'consitent': 'consistent',
 'conteinue': 'continue',
 'conterdicts': 'contradicts',
 'contineu': 'continue',
 'continieu': 'continue',
 'continuen': 'continue',
 'continun': 'continue',
 'contune': 'continue',
 'conver': 'convert',
 'corn': 'cron',
 'correrlt': 'correctly',
 'correrlty': 'correctly',
 'correst': 'correct',
 'corrested': 'corrected',
 'corresth': 'correct',
 'correstly': 'correctly',
 'correstt': 'correct',
 'corret': 'correct',
 'correted': 'corrected',
 'corretly': 'correctly',
 'corretlys': 'correctly',
 'corrlty': 'correctly',
 'corrst': 'correct',
 'cotnext': 'context',
 'cotnexts': 'contexts',
 'cotnue': 'continue',
 'couldnt': "couldn't",
 'cra': 'can',
 'craete': 'create',
 'crating': 'creating',
 'creat': 'create',
 'creatig': 'creating',
 'creatiing': 'creating',
 'critisize': 'criticize',
 'csoue': 'source',
 'curernt': 'current',
 'currest': 'current',
 'currestly': 'currently',
 'curreststate': 'current state',
 'curret': 'current',
 'curretly': 'currently',
 'dahes': 'dashes',
 'dashbord': 'dashboard',
 'dashs': 'dashes',
 'databae': 'database',
 'databaes': 'database',
 'databse': 'database',
 'datbase': 'database',
 'dcontext': 'context',
 'deaom': 'daemon',
 'deced': 'decided',
 'decesion': 'decision',
 'decison': 'decision',
 'decisons': 'decisions',
 'defaul': 'default',
 'definately': 'definitely',
 'definitly': 'definitely',
 'defintion': 'definition',
 'deliberatly': 'deliberately',
 'dependant': 'dependent',
 'deply': 'deploy',
 'desicion': 'decision',
 'desicions': 'decisions',
 'desion': 'decision',
 'detaisl': 'details',
 'detials': 'details',
 'deveilpt': 'development',
 'develompt': 'development',
 'developmet': 'development',
 'developmetns': 'developments',
 'deveoping': 'developing',
 'deveplnmet': 'development',
 'devleoping': 'developing',
 'devloping': 'developing',
 'didnt': "didn't",
 'diernmt': 'determine',
 'diferent': 'different',
 'differnt': 'different',
 'diffrent': 'different',
 'diganise': 'diagnose',
 'diosved': 'discovered',
 'dirrect': 'direct',
 'dirrectivei': 'directive',
 'dirreft': 'direct',
 'dirret': 'direct',
 'discbed': 'described',
 'discirbueied': 'distributed',
 'discoved': 'discovered',
 'discribe': 'describe',
 'disovced': 'discovered',
 'disoved': 'discovered',
 'dissapear': 'disappear',
 'disvirtys': 'discoveries',
 'disvoced': 'discovered',
 'dittermin': 'determine',
 'docceumnt': 'document',
 'doccmuted': 'documented',
 'doccomution': 'documentation',
 'doccoumes': 'documents',
 'doccuemnt': 'document',
 'doccuemntu': 'document',
 'doccuemtn': 'document',
 'doccuemtned': 'documented',
 'doccumation': 'documentation',
 'doccuments': 'documents',
 'doccumt': 'document',
 'docuemnt': 'document',
 'documnet': 'document',
 'documneted': 'documented',
 'documnted': 'documented',
 'doen': 'done',
 'doesnt': "doesn't",
 'doest': 'does',
 'donr': 'done',
 'donwload': 'download',
 'dosnt': "doesn't",
 'dotn': "don't",
 'doubht': 'doubt',
 'downlod': 'download',
 'drif': 'drift',
 'dritef': 'drifted',
 'dupalcies': 'duplicates',
 'eahc': 'each',
 'easilly': 'easily',
 'easly': 'easily',
 'eaxplion': 'explanation',
 'ect': 'etc',
 'edn': 'end',
 'effecency': 'efficiency',
 'effecient': 'efficient',
 'effectve': 'effective',
 'effeictly': 'effectively',
 'effeive': 'effective',
 'effice': 'efficient',
 'efficeint': 'efficient',
 'efficent': 'efficient',
 'efficet': 'efficient',
 'effive': 'effective',
 'effivlty': 'effectively',
 'efice': 'efficient',
 'efroe': 'before',
 'ehac': 'each',
 'eleas': 'else',
 'eles': 'else',
 'elimnate': 'eliminate',
 'elminate': 'eliminate',
 'embarras': 'embarrass',
 'emjoie': 'emoji',
 'enache': 'enhance',
 'enad': 'end',
 'enagily': 'entirely',
 'enahcment': 'enhancement',
 'enahcnmendt': 'enhancement',
 'enatierly': 'entirely',
 'ende': 'end',
 'enfoming': 'enforcing',
 'enforcments': 'enforcements',
 'enfroced': 'enforced',
 'englsi': 'english',
 'englsih': 'english',
 'engough': 'enough',
 'ensrue': 'ensure',
 'ensuer': 'ensure',
 'enveimnrt': 'environment',
 'enveimrt': 'environment',
 'enviroment': 'environment',
 'enviromnet': 'environment',
 'envrionment': 'environment',
 'envtro': 'inventory',
 'epalin': 'explain',
 'epaxlin': 'explain',
 'epian': 'explain',
 'eplxain': 'explain',
 'epxlain': 'explain',
 'equipement': 'equipment',
 'ermove': 'remove',
 'everr': 'ever',
 'everyhing': 'everything',
 'everyrhin': 'everything',
 'everythign': 'everything',
 'exacitgn': 'existing',
 'exacpeily': 'especially',
 'exactuly': 'exactly',
 'exagerate': 'exaggerate',
 'exalty': 'exactly',
 'exapicce': 'especially',
 'exaplin': 'explain',
 'excelent': 'excellent',
 'exchage': 'exchange',
 'excpet': 'except',
 'exculde': 'exclude',
 'execue': 'execute',
 'execurete': 'execute',
 'exiing': 'existing',
 'exiisng': 'existing',
 'exising': 'existing',
 'exisng': 'existing',
 'existant': 'existent',
 'exlcude': 'exclude',
 'exling': 'explain',
 'exlpain': 'explain',
 'exlude': 'exclude',
 'expalce': 'explicit',
 'expalce2': 'explicit',
 'expaliced': 'explained',
 'expalin': 'explain',
 'expeced': 'expected',
 'expereince': 'experience',
 'experence': 'experience',
 'experiance': 'experience',
 'expidite': 'expedite',
 'explacilty': 'explicitly',
 'explalin': 'explain',
 'explicitely': 'explicitly',
 'expllain': 'explain',
 'expoice': 'experience',
 'familar': 'familiar',
 'favourable': 'favorable',
 'feahter': 'feature',
 'fearuers': 'features',
 'fearues': 'features',
 'fearuesr': 'features',
 'fearus': 'features',
 'featrue': 'feature',
 'featrues': 'features',
 'featuer': 'feature',
 'featueres': 'features',
 'featuers': 'features',
 'featurs': 'features',
 'feauere': 'feature',
 'feauers': 'features',
 'feaure': 'feature',
 'feaurees': 'features',
 'feaurers': 'features',
 'feaures': 'features',
 'feaurs': 'features',
 'feauter': 'feature',
 'feauteres': 'features',
 'feauterrs': 'features',
 'feauters': 'features',
 'feautres': 'features',
 'feild': 'field',
 'feilds': 'fields',
 'fiedex': 'fixed',
 'finalise': 'finalize',
 'finaly': 'finally',
 'finalyl': 'finally',
 'findign': 'finding',
 'findigns': 'findings',
 'flawess': 'flawless',
 'fllow': 'follow',
 'flos': 'flows',
 'flwo': 'flow',
 'flwos': 'flows',
 'foal': 'goal',
 'fobbied': 'forbidden',
 'fobbiend': 'forbidden',
 'focuse': 'focus',
 'followwed': 'followed',
 'follwed': 'followed',
 'follwo': 'follow',
 'follwoing': 'following',
 'folow': 'follow',
 'folowing': 'following',
 'fooloow': 'follow',
 'foolow': 'follow',
 'forbbin': 'forbidden',
 'forhead': 'forehead',
 'forign': 'foreign',
 'fou': 'for',
 'fouces': 'focus',
 'foucs': 'focus',
 'foward': 'forward',
 'fowarding': 'forwarding',
 'fowlwl': 'follow',
 'fraunes': 'Fraunces',
 'frmo': 'from',
 'fron': 'front',
 'fthat': 'that',
 'fuaetrers': 'features',
 'fucntion': 'function',
 'ful': 'full',
 'fules': 'rules',
 'fullow': 'follow',
 'fuly': 'fully',
 'funcauitly': 'functionality',
 'funcauutly': 'functionality',
 'functinality': 'functionality',
 'funcuail': 'functional',
 'funcuility': 'functionality',
 'funcuilty': 'functionality',
 'funcuionality': 'functionality',
 'funcuitly': 'functionality',
 'funcunt': 'functions',
 'funcuntal': 'functional',
 'funcuntil': 'functionality',
 'funcuntilty': 'functionality',
 'funcuntily': 'functionality',
 'funcuntionality': 'functionality',
 'funcutil': 'functional',
 'funcutily': 'functionality',
 'funtion': 'function',
 'funtions': 'functions',
 'fununtil': 'functional',
 'futher': 'further',
 'fveiry': 'verify',
 'gab': 'gap',
 'gallaby': 'gallery',
 'gally': 'gallery',
 'gaol': 'goal',
 'gaolas': 'goals',
 'gaols': 'goals',
 'garantee': 'guarantee',
 'gaurantee': 'guarantee',
 'gaurd': 'guard',
 'gdo': 'do',
 'generaly': 'generally',
 'genetar': 'generate',
 'gentaret': 'generate',
 'geting': 'getting',
 'geust': 'guest',
 'githook': 'git hook',
 'googel': 'google',
 'gradualy': 'gradually',
 'gratefuly': 'gratefully',
 'gratutious': 'gratuitous',
 'gret': 'great',
 'gthub': 'github',
 'guese': 'guess',
 'gueseing': 'guessing',
 'guesse': 'guess',
 'guidem': 'guide',
 'guseesi': 'guesses',
 'gusess': 'guess',
 'guset': 'guest',
 'gusse': 'guess',
 'gusses': 'guesses',
 'happend': 'happened',
 'harrass': 'harass',
 'hases': 'phases',
 'havent': "haven't",
 'heavilty': 'heavily',
 'hierachy': 'hierarchy',
 'hning': 'thing',
 'hounour': 'honor',
 'hta': 'the',
 'htat': 'that',
 'hte': 'the',
 'htere': 'there',
 'htink': 'think',
 'htis': 'this',
 'hvae': 'have',
 'hwo': 'how',
 'iamge': 'image',
 'iamges': 'images',
 'idealogy': 'ideology',
 'idenitfy': 'identify',
 'identfy': 'identify',
 'ifi': 'if',
 'ifx': 'fix',
 'ike': 'like',
 'imediately': 'immediately',
 'imgae': 'image',
 'immediatly': 'immediately',
 'immeditly': 'immediately',
 'immedolty': 'immediately',
 'imove': 'improve',
 'implemention': 'implementation',
 'importn': 'important',
 'impove': 'improve',
 'improvemnt': 'improvement',
 'improvments': 'improvements',
 'incldue': 'include',
 'independant': 'independent',
 'indeplth': 'in-depth',
 'inetact': 'interact',
 'infoamtion': 'information',
 'infomation': 'information',
 'informtion': 'information',
 'infto': 'into',
 'inlcde': 'include',
 'inlcude': 'include',
 'inlcuding': 'including',
 'insded': 'instead',
 'insead': 'instead',
 'insed': 'instead',
 'instaed': 'instead',
 'insted': 'instead',
 'insteresting': 'interesting',
 'instrictions': 'instructions',
 'intead': 'instead',
 'inteareated': 'integrated',
 'inteareted': 'integrated',
 'intehrated': 'integrated',
 'interacte': 'interact',
 'intercat': 'interact',
 'interset': 'interest',
 'interupt': 'interrupt',
 'intrest': 'interest',
 'invaild': 'invalid',
 'iport': 'import',
 'irresistable': 'irresistible',
 'isession': 'session',
 'isnt': "isn't",
 'isse': 'issue',
 'itno': 'into',
 'iwth': 'with',
 'iyt': 'it',
 'jsut': 'just',
 'knoe': 'know',
 'knowlege': 'knowledge',
 'knowlegeable': 'knowledgeable',
 'kwno': 'know',
 'lage': 'large',
 'lal': 'all',
 'langauge': 'language',
 'laso': 'also',
 'learnd': 'learned',
 'lerned': 'learned',
 'lfow': 'flow',
 'lfows': 'flows',
 'lgoin': 'login',
 'lgoing': 'login',
 'liason': 'liaison',
 'libary': 'library',
 'liek': 'like',
 'lisence': 'license',
 'lising': 'listing',
 'listsings': 'listings',
 'localg': 'local',
 'logail': 'logical',
 'logailc': 'logical',
 'logcial': 'logical',
 'logial': 'logical',
 'loign': 'login',
 'lreaned': 'learned',
 'lsit': 'list',
 'lvm': 'vlm',
 'maek': 'make',
 'maintainance': 'maintenance',
 'maintainence': 'maintenance',
 'managmenet': 'management',
 'managment': 'management',
 'mandrott': 'mandatory',
 'mandtory': 'mandatory',
 'manuever': 'maneuver',
 'mdpointer': 'md pointer',
 'meantin': 'mentioned',
 'meantion': 'mention',
 'medilty': 'methodology',
 'medotlhy': 'methodology',
 'mek': 'make',
 'mentaion': 'mention',
 'merdily': 'methodology',
 'merhldt': 'methodology',
 'merhold': 'methodology',
 'merholdy': 'methodology',
 'merthod': 'method',
 'merthold': 'methodology',
 'mesaage': 'message',
 'mesage': 'message',
 'mesntion': 'mention',
 'messgae': 'message',
 'metdoly': 'methodology',
 'methldy': 'methodology',
 'metho': 'method',
 'methodly': 'methodology',
 'methodlys': 'methodologies',
 'methold': 'method',
 'metholdgy': 'methodology',
 'metholdl': 'methodology',
 'metholds': 'methods',
 'metholdty': 'methodology',
 'metholdy': 'methodology',
 'metholdys': 'methodologies',
 'metholfdys': 'methodologies',
 'metodly': 'methodology',
 'metohldy': 'methodology',
 'metohldys': 'methodologies',
 'metoldy': 'methodology',
 'metthodly': 'methodology',
 'minal': 'minimal',
 'minauil': 'minimal',
 'mising': 'missing',
 'miskes': 'mistakes',
 'miskt': 'mistakes',
 'mispell': 'misspell',
 'mitargion': 'mitigation',
 'mitnagion': 'mitigation',
 'mmerdoldy': 'methodology',
 'modauler': 'modular',
 'moduaelied': 'modularized',
 'modualeied': 'modularized',
 'modualieze': 'modularize',
 'modualiezed': 'modularized',
 'modualized': 'modularized',
 'modualr': 'modular',
 'moduelr': 'modular',
 'moduerl': 'modular',
 'modulare': 'modular',
 'moee': 'more',
 'moniter': 'monitor',
 'mrege': 'merge',
 'mroe': 'more',
 'msot': 'most',
 'msut': 'must',
 'mteh': 'the',
 'mutiple': 'multiple',
 'nad': 'and',
 'nadn': 'and',
 'nalyize': 'analyze',
 'nalys': 'analyze',
 'nalzye': 'analyze',
 'naother': 'another',
 'nayhing': 'anything',
 'neahc': 'enhance',
 'neccessarily': 'necessarily',
 'neccessary': 'necessary',
 'necesary': 'necessary',
 'ned': 'need',
 'neded': 'needed',
 'neer': 'never',
 'nees': 'needs',
 'neetholdy': 'methodology',
 'negotiaton': 'negotiation',
 'newist': 'newest',
 'nmeantion': 'mention',
 'nontechail': 'non-technical',
 'noticable': 'noticeable',
 'nseaked': 'sneaked',
 'nte': 'the',
 'nto': 'not',
 'nxt': 'next',
 'oc': 'doc',
 'ocassion': 'occasion',
 'occassion': 'occasion',
 'occured': 'occurred',
 'ocmaplex': 'complex',
 'ocs': 'docs',
 'ofent': 'often',
 'offical': 'official',
 'ohter': 'other',
 'ohther': 'other',
 'ommission': 'omission',
 'onyl': 'only',
 'opne': 'open',
 'oppurtunity': 'opportunity',
 'oredered': 'ordered',
 'orignal': 'original',
 'otehr': 'other',
 'otehrwise': 'otherwise',
 'outr': 'our',
 'oyu': 'you',
 'oyur': 'your',
 'paeg': 'page',
 'pag': 'page',
 'palces': 'places',
 'paln': 'plan',
 'palns': 'plans',
 'pannel': 'panel',
 'pannles': 'panels',
 'parrallel': 'parallel',
 'particluar': 'particular',
 'particulary': 'particularly',
 'pavillion': 'pavilion',
 'peice': 'piece',
 'pemnrlty': 'permanently',
 'peole': 'people',
 'peoople': 'people',
 'perferred': 'preferred',
 'perfomance': 'performance',
 'performace': 'performance',
 'perhapse': 'perhaps',
 'permanetly': 'permanently',
 'permeit': 'permanent',
 'permently': 'permanently',
 'permeriley': 'permanently',
 'permerilty': 'permanently',
 'permerily': 'permanently',
 'permernlty': 'permanently',
 'perminte': 'permanently',
 'pernvet': 'prevent',
 'perspic': 'perspective',
 'persue': 'pursue',
 'peserve': 'preserve',
 'pgae': 'page',
 'picure': 'picture',
 'pivioting': 'pivoting',
 'pivitoing': 'pivoting',
 'plagerize': 'plagiarize',
 'planed': 'planned',
 'planing': 'planning',
 'playright': 'playwright',
 'pointles': 'pointless',
 'poit': 'point',
 'poratble': 'portable',
 'porduction': 'production',
 'porejct': 'project',
 'porgees': 'progress',
 'porived': 'provide',
 'porject': 'project',
 'pormpt': 'prompt',
 'pormpts': 'prompts',
 'pormtp': 'prompt',
 'portized': 'prioritized',
 'porudction': 'production',
 'posession': 'possession',
 'posible': 'possible',
 'possbile': 'possible',
 'possilbe': 'possible',
 'povied': 'provide',
 'prefered': 'preferred',
 'preffered': 'preferred',
 'preiod': 'period',
 'premnrtly': 'permanently',
 'presance': 'presence',
 'preseriv': 'preserve',
 'previwe': 'preview',
 'prgesse': 'progress',
 'prgoress': 'progress',
 'primarly': 'primarily',
 'priveiw': 'preview',
 'privew': 'preview',
 'priviledge': 'privilege',
 'priviledges': 'privileges',
 'probalby': 'probably',
 'probaly': 'probably',
 'probelms': 'problems',
 'probem': 'problem',
 'proccess': 'process',
 'procduaion': 'production',
 'proces': 'process',
 'proding': 'producing',
 'producation': 'production',
 'proejct': 'project',
 'proffesionally': 'professionally',
 'progees': 'progress',
 'progerss': 'progress',
 'progese': 'progress',
 'progess': 'progress',
 'progres': 'progress',
 'progresse': 'progress',
 'projcet': 'project',
 'projct': 'project',
 'projets': 'projects',
 'projoect': 'project',
 'promonent': 'prominent',
 'promtps': 'prompts',
 'propt': 'prompt',
 'proptized': 'prioritized',
 'propts': 'prompts',
 'prossible': 'possible',
 'protgess': 'progress',
 'protioly': 'priority',
 'protized': 'prioritized',
 'protocal': 'protocol',
 'provde': 'provide',
 'proveid': 'provide',
 'provied': 'provide',
 'psecilft': 'specific',
 'ption': 'option',
 'queistion': 'question',
 'quesion': 'question',
 'quesiotnions': 'questions',
 'queston': 'question',
 'questuins': 'questions',
 'questuoions': 'questions',
 'quetion': 'question',
 'qustion': 'question',
 'reacher': 'research',
 'reachers': 'reached',
 'readablely': 'readably',
 'readin': 'reading',
 'readly': 'really',
 'readt': 'ready',
 'reahc': 'reach',
 'reahced': 'reached',
 'reahcer': 'research',
 'reaienre': 'renders',
 'realise': 'realize',
 'realpcement': 'replacement',
 'realted': 'related',
 'realtef': 'related',
 'realy': 'really',
 'reasher': 'research',
 'reasuslts': 'results',
 'reatled': 'related',
 'reauslet': 'results',
 'reccemiond': 'recommend',
 'recceomnd': 'recommend',
 'reccmaids': 'recommend',
 'reccoemdn': 'recommend',
 'reccoemned': 'recommend',
 'reccoend': 'recommend',
 'reccomend': 'recommend',
 'reccomendation': 'recommendation',
 'reccomendations': 'recommendations',
 'reccomendion': 'recommendation',
 'receond': 'rescored',
 'recerlt': 'recently',
 'recert': 'recent',
 'recet': 'recent',
 'receve': 'receive',
 'recieve': 'receive',
 'recieved': 'received',
 'recoend': 'recommend',
 'recomemd': 'recommend',
 'recomend': 'recommend',
 'recomendation': 'recommendation',
 'recomendations': 'recommendations',
 'recomendion': 'recommendation',
 'recommdation': 'recommendation',
 'recommendions': 'recommendations',
 'recommenions': 'recommendations',
 'reconize': 'recognize',
 'recrod': 'record',
 'redeolplty': 'redeploy',
 'redeoply': 'redeploy',
 'redeply': 'redeploy',
 'redploy': 'redeploy',
 'redpoly': 'redeploy',
 'reduculous': 'ridiculous',
 'reduendtent': 'redundant',
 'reeverlt': 'relevant',
 'referal': 'referral',
 'regester': 'register',
 'regiter': 'register',
 'regsiter': 'register',
 'reguardless': 'regardless',
 'reivew': 'review',
 'reiveww': 'review',
 'rela': 'real',
 'relavent': 'relevant',
 'relevent': 'relevant',
 'relized': 'realized',
 'remaber': 'remember',
 'remaing': 'remaining',
 'rember': 'remember',
 'remore': 'remote',
 'remvoe': 'remove',
 'reneder': 'render',
 'reoprt': 'report',
 'reort': 'report',
 'repetative': 'repetitive',
 'repitition': 'repetition',
 'replacment': 'replacement',
 'reponse': 'response',
 'repotr': 'report',
 'repots': 'reports',
 'reprot': 'report',
 'repsoed': 'respond',
 'repsoedn': 'respond',
 'req3uiezmnt': 'requirement',
 'reqeamnest': 'requirements',
 'reqeima': 'requirement',
 'reqeimasmints': 'requirements',
 'reqest': 'request',
 'reqeuainst': 'requirements',
 'reqeuismnt': 'requirement',
 'reqeusimenrs': 'requirements',
 'reqeusiment': 'requirement',
 'reqeusiments': 'requirements',
 'reqeusinents': 'requirements',
 'reqeusisnuments': 'requirements',
 'reqeusts': 'requests',
 'reqeyimnerts': 'requirements',
 'reqiurements': 'requirements',
 'requeimnts': 'requirements',
 'requesmnent': 'requirement',
 'requiemnts': 'requirements',
 'requiemrnt': 'requirement',
 'requiemrnting': 'requirement',
 'requiemtns': 'requirements',
 'requienrts': 'requirements',
 'requierment': 'requirement',
 'requiermtn': 'requirement',
 'requiermtns': 'requirements',
 'requimenrt': 'requirement',
 'requimenrtimtn': 'requirements',
 'requiments': 'requirements',
 'requimrents': 'requirements',
 'requiremetns': 'requirements',
 'requiremnts': 'requirements',
 'requirment': 'requirement',
 'requirments': 'requirements',
 'requniments': 'requirements',
 'requriements': 'requirements',
 'requriments': 'requirements',
 'requset': 'request',
 'reserach': 'research',
 'resistent': 'resistant',
 'respectfull': 'respectful',
 'respnse': 'response',
 'responce': 'response',
 'responsable': 'responsible',
 'restaraunt': 'restaurant',
 'resturant': 'restaurant',
 'resurfed': 'resurfaced',
 'retening': 'repeating',
 'reuaquest': 'requested',
 'reuiments': 'requirements',
 'reuqested': 'requested',
 'reuqmnet': 'requirement',
 'reveiw': 'review',
 'reveiwing': 'reviewing',
 'reviei': 'review',
 'revies': 'reviews',
 'rezliaze': 'realize',
 'riddiculous': 'ridiculous',
 'rleaited': 'related',
 'rmeote': 'remote',
 'rmeove': 'remove',
 'rmote': 'remote',
 'rpoject': 'project',
 'rqueasitmns': 'requirements',
 'runing': 'running',
 'runnign': 'running',
 'sacable': 'scalable',
 'sacle': 'scale',
 'sacleable': 'scalable',
 'sacrafice': 'sacrifice',
 'saftey': 'safety',
 'scalbitly': 'scalability',
 'scareen': 'screen',
 'scarne': 'scan',
 'sccess': 'success',
 'sceen': 'screen',
 'schroll': 'scroll',
 'scond': 'second',
 'screeb': 'screen',
 'screeen': 'screen',
 'screem': 'screen',
 'scren': 'screen',
 'scusse': 'success',
 'seaction': 'section',
 'seccind': 'second',
 'seccond': 'second',
 'seccuity': 'security',
 'secculrt': 'secure',
 'seccult': 'security',
 'secculty': 'security',
 'seccure': 'secure',
 'seccuriety': 'security',
 'sechudle': 'schedule',
 'secind': 'second',
 'secratary': 'secretary',
 'secuirty': 'security',
 'securty': 'security',
 'secusse': 'success',
 'seesion': 'session',
 'seesioon': 'session',
 'seeure': 'secure',
 'semmingly': 'seemingly',
 'seperate': 'separate',
 'seprate': 'separate',
 'sesion': 'session',
 'sessin': 'session',
 'sghould': 'should',
 'shauld': 'should',
 'shoind': 'showing',
 'shold': 'should',
 'shoudl': 'should',
 'shoudlt': "shouldn't",
 'shouldnt': "shouldn't",
 'shto': 'shot',
 'shtos': 'shots',
 'shts': 'shots',
 'shuold': 'should',
 'shure': 'sure',
 'signifantly': 'significantly',
 'similer': 'similar',
 'similiar': 'similar',
 'sincerly': 'sincerely',
 'singup': 'signup',
 'sinlge': 'single',
 'sked': 'asked',
 'skilsl': 'skills',
 'slect': 'select',
 'smae': 'same',
 'snas': 'sans',
 'snes': 'sense',
 'socail': 'social',
 'socue': 'source',
 'soem': 'some',
 'soeming': 'something',
 'soemthing': 'something',
 'soemthng': 'something',
 'soemtihng': 'something',
 'solation': 'isolation',
 'solion': 'solution',
 'soluction': 'solution',
 'someting': 'something',
 'somoe': 'some',
 'soucue': 'source',
 'specificaly': 'specifically',
 'specifiy': 'specify',
 'speicf': 'specific',
 'staing': 'staging',
 'stategy': 'strategy',
 'statment': 'statement',
 'statrt': 'start',
 'stlye': 'style',
 'stlyes': 'styles',
 'strenth': 'strength',
 'strickly': 'strictly',
 'structre': 'structure',
 'studing': 'studying',
 'styel': 'style',
 'suapbase': 'supabase',
 'suapvbase': 'supabase',
 'subejct': 'subject',
 'substract': 'subtract',
 'succesful': 'successful',
 'successfull': 'successful',
 'sucess': 'success',
 'sucessful': 'successful',
 'sued': 'used',
 'sueegto': 'suggestion',
 'sugestion': 'suggestion',
 'sugestions': 'suggestions',
 'suggestin': 'suggesting',
 'sujbect': 'subject',
 'supabse': 'supabase',
 'supaebse': 'supabase',
 'supbase': 'supabase',
 'suposed': 'supposed',
 'suppoed': 'supposed',
 'suppsoe': 'suppose',
 'supress': 'suppress',
 'suprize': 'surprise',
 'surpress': 'suppress',
 'sute': 'sure',
 'systemmatic': 'systematic',
 'taclked': 'tackled',
 'taht': 'that',
 'taks': 'task',
 'taksing': 'tasking',
 'tast': 'taste',
 'tat': 'that',
 'teachail': 'technical',
 'teachial': 'technical',
 'teachil': 'technical',
 'techail': 'technical',
 'techanil': 'technical',
 'techinal': 'technical',
 'techology': 'technology',
 'teh': 'the',
 'tehcail': 'technical',
 'tehcnical': 'technical',
 'temperture': 'temperature',
 'tempory': 'temporary',
 'tesst': 'test',
 'teypo': 'typo',
 'thats': "that's",
 'theather': 'theater',
 'thee': 'there',
 'theis': 'these',
 'thene': 'theme',
 'theter': 'there',
 'thier': 'their',
 'thier2': 'their',
 'thisi': 'this',
 'thnik': 'think',
 'tho': 'though',
 'thogh': 'thought',
 'thoguh': 'though',
 'thoiugh': 'thought',
 'throug': 'through',
 'thruout': 'throughout',
 'ths': 'this',
 'thsi': 'this',
 'thsoe': 'those',
 'thught': 'thought',
 'thuis': 'this',
 'tihs': 'this',
 'tital': 'title',
 'tlye': 'type',
 'tomes': 'times',
 'tommorow': 'tomorrow',
 'tommorrow': 'tomorrow',
 'toreivew': 'review',
 'totaly': 'totally',
 'towrad': 'toward',
 'tradegy': 'tragedy',
 'tranfer': 'transfer',
 'transperent': 'transparent',
 'truely': 'truly',
 'trun': 'turn',
 'truned': 'turned',
 'tst': 'test',
 'twelth': 'twelfth',
 'typcial': 'typical',
 'uder': 'under',
 'udner': 'under',
 'unacompanied': 'unaccompanied',
 'unbelieveable': 'unbelievable',
 'uncertainity': 'uncertainty',
 'underasntd': 'understand',
 'underate': 'underrate',
 'undersand': 'understand',
 'undersantd': 'understand',
 'undersatnd': 'understand',
 'undersnatd': 'understand',
 'understadn': 'understand',
 'unfished': 'unfinished',
 'unfortunatley': 'unfortunately',
 'unfortunatly': 'unfortunately',
 'unill': 'until',
 'unkonow': 'unknown',
 'unneccessary': 'unnecessary',
 'unnesseary': 'unnecessary',
 'unoticed': 'unnoticed',
 'untill': 'until',
 'unuseful': 'useless',
 'updte': 'update',
 'uplado': 'upload',
 'uplaod': 'upload',
 'uplod': 'upload',
 'urlzie': 'utilize',
 'usanble': 'usable',
 'usfull': 'useful',
 'usign': 'using',
 'usnerdtnad': 'understand',
 'usppose': 'suppose',
 'usre': 'user',
 'usres': 'users',
 'usslesor': 'useless',
 'usualy': 'usually',
 'usualyl': 'usually',
 'utlzie': 'utilize',
 'varify': 'verify',
 'vauge': 'vague',
 'vefity': 'verify',
 'verfiy': 'verify',
 'verifyh': 'verify',
 'verison': 'version',
 'veriy': 'verify',
 'verrify': 'verify',
 'versaion': 'version',
 'verson': 'version',
 'veryiging': 'verifying',
 'vesaion': 'version',
 'viw': 'view',
 'waht': 'what',
 'wasrte': 'waste',
 'wasste': 'waste',
 'wath': 'what',
 'watn': 'want',
 'wether': 'whether',
 'whcih': 'which',
 'wheather': 'whether',
 'whitch': 'which',
 'whne': 'when',
 'whoel': 'whole',
 'whould': 'would',
 'wich': 'which',
 'widnso': 'window',
 'wiht': 'with',
 'wil': 'will',
 'witrj': 'with',
 'wnat': 'want',
 'wok': 'work',
 'woking': 'working',
 'wokr': 'work',
 'wont': "won't",
 'workflwos': 'workflows',
 'wot': "won't",
 'woudl': 'would',
 'woudlnt': "wouldn't",
 'wouldnt': "wouldn't",
 'writen': 'written',
 'wrk': 'work',
 'wrko': 'work',
 'wrng': 'wrong',
 'wroekd': 'worked',
 'wroekrs': 'workers',
 'wrofkflow': 'workflow',
 'wrok': 'work',
 'wrokflows': 'workflows',
 'wrokflwos': 'workflows',
 'wrokfow': 'workflow',
 'wroking': 'working',
 'wtih': 'with',
 'wwhen': 'when',
 'wwill': 'will',
 'wwithout': 'without',
 'yto': 'to'}

PHRASE_MAP = {'(a) Complete them on mock first thisi the corrst apporch': '(a) Complete them on mock first this is the correct approach',
 'dont suggest': "don't suggest",
 'dont stop at a phase': "don't stop at a phase",
 'dont use snas': "don't use snas",
 'but dont exist yet': "but don't exist yet",
 'i dont think': "i don't think",
 'if you dont know': "if you don't know",
 'we dont have to': "we don't have to",
 'we dont wasste': "we don't wasste",
 'you dont have to': "you don't have to",
 '.,d docthat': '.md doc that',
 'AGENTS.mdPointer': 'AGENTS.md pointer',
 'DID NOT REQUESSAT': 'DID NOT REQUEST',
 'GIVE ME APROMTP': 'GIVE ME A PROMPT',
 'I CAN YOU WITH ANY TAKS': 'I CAN USE WITH ANY TASK',
 'TO IMIT YOU TO': 'TO LIMIT YOU TO',
 'a real use would': 'a real user would',
 'a seccind dire tion on': 'a second direction on',
 'accept al lthe': 'accept all the',
 'again wit the': 'again with the',
 'als makea': 'also make a',
 'als owill': 'also will',
 'am ubalbeto': 'am unable to',
 'analysis e make': 'analysis we make',
 'analysis f the ui': 'analysis of the ui',
 'and account and being': 'an account and being',
 'and dox context': 'and docs context',
 'ant ai': 'anti ai',
 'ant i ai': 'anti ai',
 'anti aui ui': 'anti ai ui',
 'are named differ': 'are named differently',
 'are supported to compelt': 'are supposed to complete',
 'are update to date': 'are up to date',
 'as ifi i': 'as if i',
 'asked u to do': 'asked you to do',
 'ati ai': 'anti ai',
 'auto pus hto': 'auto push to',
 'avid aking': 'avoid asking',
 'back round': 'background',
 'basedo n': 'based on',
 'before you lied t u': 'before you listed to you',
 'beuse hen': 'because when',
 'blocking ue from': 'blocking us from',
 'brain strom': 'brainstorm',
 'brain stron and plan': 'brainstorm and plan',
 'brian storming': 'brainstorming',
 'but you did n why': 'but you did not why',
 'cn not do the y you have': 'can not do that you have',
 'con job': 'cron job',
 'constaife': 'constraint',
 'continue asl ouou have revert to fast session': 'continue also you have reverted to last session',
 'continue id oyu fx': 'continue if you fix',
 'dat abut': 'date but',
 'did you readly he system': 'did you really read the system',
 'directive  ive before': 'directive i gave before',
 'dirrect expalce dirrect to put': 'direct explicit direction to put',
 'discied a s needed': 'decided as needed',
 'do stop set it up': 'do not set it up',
 'do thin in a': 'do this in a',
 'docs a nd work': 'docs and work',
 'dow nal lthe': 'down all the',
 'drif form': 'drift from',
 'effivlty slecetthem': 'effectively select them',
 'em dahes': 'em dashes',
 'etc do just stop and the end': "etc don't just stop at the end",
 'explain you recommendations': 'explain your recommendations',
 'fi it': 'fix it',
 'follow es the': 'follows the',
 'follow ithe': 'follow the',
 'follow th anti a ui': 'follow the anti ai ui',
 'follwo thecorrest work flow': 'follow the correct work flow',
 'for ech question': 'for each question',
 'for mit so': 'for me so',
 'form hte': 'from the',
 'form the doc': 'from the doc',
 'form the featuers in': 'from the features in',
 'form the perspic form': 'from the perspective of',
 'form the requirement from that i made': 'from the requirements that i made',
 'fowlwl othe exact': 'follow the exact',
 'fro msome': 'from some',
 'from iew the': 'from viewing the',
 'fron end': 'front end',
 'frond end': 'front end',
 'front en and': 'front end and',
 'gap analysis uncover more': 'gap analysis uncovers more',
 'googel sing oauth': 'google sign-in oauth',
 'has yoto ask': 'have to ask',
 'hen a ai': 'when an ai',
 'how to fix the int  the feature': 'how to fix the intent - the feature',
 'hte enad of': 'the end of',
 'i need tto knw': 'i need to know',
 'i need you to more that': 'i need you to remove that',
 'i reuqensAT HERE': 'i requested AT HERE',
 'iddo nto': 'i do not',
 'ifs ita': 'if its a',
 'in baed on protioly': 'based on priority',
 'int o an ew oantier': 'into a new container',
 'int ot': 'into',
 'intery seprted': 'entirely separated',
 'is be best way': 'is the best way',
 'is nt a': 'is not a',
 'it it should': 'it should',
 'know yto to': 'know how to',
 'lack luster': 'lackluster',
 'make a me a': 'make me a',
 'make am amrket palece app': 'make a marketplace app',
 'make blth as themes': 'make both as themes',
 'make ma doc': 'make me a doc',
 'make ma doc that': 'make me a doc that',
 'make ma e a full': 'make me a full',
 'make ma feature': 'make me a feature',
 'make ma feature break': 'make me a feature break',
 'make sute the aremove thing ou nact do form': "make sure to remove the things you can't do from",
 'mandrott y': 'mandatory',
 'methodl y ,': 'methodology ,',
 'metholdl y': 'methodology',
 'n ot mention': 'not mention',
 'nextsession': 'next session',
 'no em dashs': 'no em dashes',
 'no od a e2e human tst': 'now do an e2e human test',
 'only the pen of': 'only the pane of',
 'or ask a taks': 'or ask a task',
 'out fox context': 'out of context',
 'over hall': 'overhaul',
 'phase ix the uto git deaom': 'phase fix the auto git daemon',
 'pros and con of': 'pros and cons of',
 'psecilft t iso': 'specific ISO',
 'pull form hte repo': 'pull from the repo',
 'pull form repo': 'pull from repo',
 'pull form the repo': 'pull from the repo',
 'pus hto the repo': 'push to the repo',
 'remote reposwe are': 'remote repos we are',
 'run out fox': 'run out of',
 'services sso you': 'services so you',
 'so i an review': 'so i can review',
 'stand ablone': 'standalone',
 'sto see': 'to see',
 'supa base': 'supabase',
 't o bedoccuemtned': 'to be documented',
 'tes t eist': 'test exist',
 'that hta pp work': 'that the app works',
 'that we mad and': 'that we made and',
 'the .md remote you made': 'the .md report you made',
 'the antu i ai ui aurts prompts': 'the anti ai ui audits prompts',
 'the key constaife': 'the key constraint',
 'the pa should': 'the plan should',
 'the quesion our asking you': "the question you're asking",
 'the question our asking': "the question you're asking",
 'this you pan you made coamplit': 'this plan you made complete',
 'thn e yo need': 'then you need',
 'thoguhhyes i will': 'though. yes i will',
 'unlessi  ellaince': 'unless i explicitly',
 'use cse': 'use case',
 'view hre screen': 'view the screen',
 'was miss reading': 'was misreading',
 'waste oftime': 'waste of time',
 'whati s the': 'what is the',
 'with out my': 'without my',
 'with out my direct': 'without my direct',
 'with out the infoamtion': 'without the information',
 'work flow e made befoerw': 'work flow we made before',
 'would have save work': 'would have saved work',
 'yesi  said': 'yes i said',
 'yesi said': 'yes i said',
 'yo ucna': 'you can',
 'yo uframe': 'you frame',
 'yo uread an underasnd': 'you read and understand',
 'you di not': 'you did not',
 'you reasoning': 'your reasoning',
 'you suggestion': 'your suggestion',
 'youcan': 'you can',
 'your sub agets skills': 'your subagent skills'}
